defaults: &defaults

development:
  <<: *defaults
  douban_key:
  douban_secret:
  app_url:
  faye_url:
  faye_client_url:

test:
  <<: *defaults

production:
  <<: *defaults
  douban_key:
  douban_secret:
  app_url:
  faye_url:
  faye_client_url:
